
#-------------------------------
# General Site Settings

title: Zach Urich
description: Design and Code
email: re.jo@live.com

menu:
- {name: Projects, url: '#work', color: 'blue'}
- {name: Activity, url: '#activity', color: 'green'}

callToAction:
- {name: Contact, url: '#contact', color: 'red'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'This is Zach Urichs, a designer and front-end developer, personal website'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
#-------------------------------
# Work Section

projects:
- {name: Backpack, folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: Santa's Helpers, folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: Test, folder: 'proj-3', file: 'projects/proj-3.html'}



#-------------------------------
