
#-------------------------------
# General Site Settings

title: Zach Urich
description: Design and Code
email: re.jo@live.com
#-------------------------------

# Define navigation links here
menu:
- {name: Projects, url: '#work', color: 'blue'}
- {name: Activity, url: '#activity', color: 'green'}

callToAction:
- {name: Contact, url: '#contact', color: 'red'}
#-------------------------------

# Define section headings
section-1: Projects
section-2:
- {name: Activity, description: "weubfiweybfi"}
section-3: Contact
#-------------------------------

# Define footer content here, including social media link
copyright:
- {text: 'Copyright 2016 Zach Urich'}

socialLinks:
- {url: 'https://twitter.com/zach462', icon: 'twitter'}
- {url: 'https://www.instagram.com/zachurich/', icon: 'instagram'}
- {url: 'https://dribbble.com/ZachUrich', icon: 'dribbble'}
- {url: 'https://www.linkedin.com/in/zach-urich', icon: 'linkedin'}
#-------------------------------

# Define project details here
projects:
- {name: Backpack, folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: Santa's Helpers, folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: AskBryan, folder: 'proj-3', file: 'projects/proj-3.html'}
#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Zach Urich is a designer and front-end developer'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
